### ISSUE TITLE
Pop-up Calendar on Date Fields not working

### ISSUE THREAD

**Issue by sanotto** [Sintattica/atk#23]
When using the AF_DATE_STRING flag, the Pop-up calendar doesn't show.
The problem is that the javascript that shows the calendar

`
onclick="return showCalendar('fecha_de_cierre[date]', 'fecha_de_cierre[date]', 'dd/mm/y', false, false);"
`
is using the "Name" attribute and it should be using the id attribute in order to specify the element.
The code uses:
`
onclick="return showCalendar('fecha_de_cierre[date]', 'fecha_de_cierre[date]', 'dd/mm/y', false, false);" type="button">  
`

Refering to this element:
`
 <input id="Ctacte_Maestro_fecha_de_cierre" class="atkdateattribute form-control" name="fecha_de_cierre[date]" value="" size="10" type="text">
`
The code should be:

`
onclick="return showCalendar('Ctacte_Maestro_fecha_de_cierre', 'Ctacte_Maestro_fecha_de_cierre', 'dd/mm/y', false, false);" type="button">  
`
The compromised code is in Attributes/DateAttribute in method "draw"

**Comment by michelerota** [comment]
Thanks. Fix on da1a38da819e36781b546254fa54e9dc0e0f5d3f
