### ISSUE TITLE
Proposal, add new node flag NF_ADD_BUTTON

### ISSUE THREAD

**Issue by sanotto** [Sintattica/atk#24]
Similar to NF_ADD_LINK but renders a Button.
Implementation sugestions:
-Rename AF_NODE_SPECIFIC5 to NF_ADD_BUTTON (The NF_SPECIFIC* are only used in TreeNode only to NF_SPECIFIC4, so 5 is unused)

In Admin Handler's renderAdminPages Method:
```
 public function renderAdminPage()
    {
        $res = [];
        if ($this->m_node->hasFlag(Node::NF_NO_ADD) == false && $this->m_node->allowed('add')) {
                        if (!$this->m_node->hasFlag(Node::NF_ADD_LINK) and  !$this->m_node->hasFlag(Node::NF_ADD_BUTTON) ) { // otherwise, in adminPage, an add link will be added.
                // we could get here because of a reject.
                $record = $this->getRejectInfo();

                $res[] = $this->invoke('addPage', $record);
            }
        }
        $res[] = $this->invoke('adminPage');

        return $res;
    }```
in AdminHandler's getAddLinkMethod:

```
 public function getAddLink()
    {
        $atk = Atk::getInstance();
        $node = $atk->atkGetNode($this->invoke('getAddNodeType'));

        if (!$node->hasFlag(Node::NF_NO_ADD) && $node->allowed('add')) {
            $label = $node->text('link_'.$node->m_type.'_add', null, '', '', true);
            if (empty($label)) {
                // generic text
                $label = Tools::atktext('add', 'atk');
            }
            if ($node->hasFlag(Node::NF_ADD_LINK)) {
                $addurl = $this->invoke('getAddUrl', $node);
                return Tools::href($addurl, $label, SessionManager::SESSION_NESTED);
                        }
                        if ($node->hasFlag(Node::NF_ADD_BUTTON)) {
                $addurl = $this->invoke('getAddUrl', $node);
                                $label="<button type='button' class='btn btn_saveandclose atkdefaultbutton btn-primary'>".$label."</button>";
                return Tools::href($addurl, $label, SessionManager::SESSION_NESTED);
                        }

        }

        return '';
    }

```
And in Node.php:

```
/**
     * Specific node flag 4.
     */
    const NF_SPECIFIC_4 = 268435456;

    /**
     * Add Button.
     */
    const NF_ADD_BUTTON = 536870912;

```

**Comment by michelerota** [comment]
It's better to use custom css styles, instead of introducing a new flag.
