### ISSUE TITLE
atk 9 render table

### ISSUE THREAD

**Issue by abalest14** [Sintattica/atk#26]
we are migrating an application from atk 6 to atk 9, we have did most of the changes but one its difficult to resolve. in the application have many reports and we use:
`        $tr = &atknew("atk.utils.atktablerenderer");
        $output.= $tr->render($tableData, TBL_DATA, "recordlist");   
      return $output;         
`
to create an html table, we try this on atk 9 but dosen't work:
`$tr = new Ui();
$output .= $tr->renderList($tableData,'utenti');
return $output;`

what wrong?
thanks

**Comment by michelerota** [comment]
In a node action, try with:

$recordset = $this->select()->getAllRows();
$recordList = new HtmlRecordList();
$recordList->setExportingCSVToFile(false);

return $recordList->render($this, $recordset);

**Comment by abalest14** [comment]
the solution you proposed require to have a node based on a table, our report collect data from different nodes and even from external applications db. Wich other options we have to make work it.
thanks

**Comment by michelerota** [comment]
In this case, simply make your own function to render a table, or use some external library. The atktablerenderer was removed from atk9 because not strictly useful for the framework.
If you feel adventurous, you could try with a static Datagrid
