### ISSUE TITLE
patch to 8.2

### ISSUE THREAD

**Issue by badpenguin** [Sintattica/atk#27]
Do you accept patches in order to add my fixes to your 8.2 branch? Or i can save my time?
I'm already in sync with your 8.2.

https://github.com/Sintattica/atk/network

**Comment by michelerota** [comment]
Ciao Antonio, fai pure delle pull request, poi ci penserà lcamozzi (Luca Camozzi) a verificare se integrarle o no.

Grazie e buona giornata!
Michele
