### ISSUE TITLE
Multilingual attributes, document templates and MetaNodes disappeared ?

### ISSUE THREAD

**Issue by Samuel-BF** [Sintattica/atk#39]
Hello,

I've updated the [atkdemo](https://github.com/atkphpframework/atkdemo) to a [new demo](https://github.com/Samuel-BF/atk9demo) for Atk9. I hit some regressions in Atk9, so I proposed patches ([1](https://github.com/Sintattica/atk/pull/35), [2](https://github.com/Sintattica/atk/pull/36), [3](https://github.com/Sintattica/atk/pull/37) & [4](https://github.com/Sintattica/atk/pull/38))

But I was not able to reproduce lesson6 of the original demo (which was about MetaNodes, Nodes that get their Attributes based on the columns of the corresponding table, table name being guessed based on Node name), lesson7 (part with opendocument templates) and lesson8 (about Internationalization inside the database - row-based and column-based). These functionality disappeared ? If not, how to use them ?

Thanks for your wonderful work on Atk. Apart from this small difficulties, i consider atk9demo to be ready now. Would it be possible for you to take over it, or add a link into the documentation of Atk (or readme.md), after a review (as a beginner, I may not have done things "the right way") ? Thanks!

**Comment by michelerota** [comment]
Yes, they disappeared
