### ISSUE TITLE
Archiving of the @atkphpframework organization

### ISSUE THREAD

**Issue by PhrozenByte** [Sintattica/atk#49]
Hi,

just want to let you guys know that I've just archived the @atkphpframework organization (I was in some sort of an tidying spree :laughing:). All repos of the @atkphpframework organization got archived and I asked the GitHub support to create an redirect from the "original" [`atkphpframework/atk` repo](https://github.com/atkphpframework/atk) to your repo. By doing so the fork connection got removed and `Sintattica/atk` is now the root of its own network. Together with large deprecation notices in the archived @atkphpframework repos I hope that all remaining users of the ATK Framework are redirected directly to you guys. This is just for your interest, you don't have to do anything :+1: 

Keep up the great work you do, I wish you all the best! :heart: 

Greetings,
Daniel

**Comment by dangamba** [comment]
Hello Daniel,
thank you!

Cheers,
Daniele
