### ISSUE TITLE
Update copyDb in TreeNode.php to match parent Node's parameters and avoid warning

### ISSUE THREAD

**Issue by jgarifuna** [Sintattica/atk#57]
# to avoid warning in atk/src/Core/TreeNode.php to match parent's copyDb method:
                change:
                    public function copyDb(&$record, $mode = 'copy')

                to:
                    public function copyDb(&$record, $mode = 'copy')

**Comment by Samuel-BF** [comment]
Fixed in 87c98e1fc.
