### ISSUE TITLE
Fix to add default action template to renderAction()

### ISSUE THREAD

**Issue by jgarifuna** [Sintattica/atk#58]
When confirmAction() is called with a non-default action, the system crashes. The way legacy ATK dealt with this was by using the default template "action.tlp". Below is the fix for this for ATK 9.1+:

File: vendor/sintattica/atk/src/Ui/Ui.php

    public function renderAction($action, $vars, $module = '')
    {
        // Start: Added by Jorge Garifuna from legacy ATK and using "$this->m_smarty->templateExists" instead of "$this->m_theme->tplPath"
        $tpl = "action_$action.tpl";
        if (!$this->m_smarty->templateExists($tpl)) // no specific theme for this action
        {
            $tpl = "action.tpl";
        }

        // old code: return $this->render("action_$action.tpl", $vars, $module);
        return $this->render($tpl, $vars, $module);
    }

**Comment by NGjata** [comment]
Merging this on v9.2.2
