### ISSUE TITLE
SETUP FOR Admin LTE Theme with 9.2 Version

### ISSUE THREAD

**Issue by AJITPRASADDIXIT** [Sintattica/atk#63]
I request guidance how to configure the theme for ark demo

I am able to install demo and work with demo but not able to get the theme set

I am running on IIS and php 7.2

My url is atkdemo.localhost

Please guide

**Comment by NGjata** [comment]
You can try to set up our new skeleton: https://github.com/Sintattica/atk-skeleton.git . Here you can see how to bootstrap the application.
