### ISSUE TITLE
ATK skeleton for 9.9.9

### ISSUE THREAD

**Issue by davide-italy** [Sintattica/atk#70]
Hi,

I used ATK in the past (and I even fixed some bugs to use MSSQL as a database).

Now I would try it again, but I wish to start from the latest version (9.9.9).

Is it possible to have an atk-skeleton for that version?

**Comment by NGjata** [comment]
Hi, we have just updated the atk-skeleton project. You can find the repo in: https://github.com/Sintattica/atk-skeleton.git
You can use the latest release of the project.
